version: '3.8'

services:
  #our react frontend
  frontend:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src

  #A Simple API (We will fake it with another node container)
  api:
    image: node:18-alpine
    working_dir: /app
    command: npx json-server --watch db.json --host 0.0.0.0 --port 3001
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app